# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        stages: [commit]
      - id: pretty-format-json
        stages: [commit]
        files: ^(?!(.*Pipfile.lock)$).*
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.23.0
    hooks:
      - id: yamllint
        stages: [commit]
  # {% if cookiecutter.use_cloudformation == 'y' %}
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.33.0
    hooks:
      - id: cfn-python-lint
        files: ^cloudformation/.*\.(json|yml|yaml)$
        stages: [commit]
  # {% endif %}
  # {% if cookiecutter.use_terraform == 'y' %}
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
      - id: terraform_fmt
        files: ^terraform/.*(\.tf|\.tfvars)$
        stages: [commit]
      - id: terraform_docs
        files: ^terraform/.*(\.tf)$
      - id: terraform_tflint
        files: ^terraform/.*(\.tf|\.tfvars)$
      - id: terragrunt_fmt
        files: ^terraform/.*(\.hcl)$
      - id: terraform_tfsec
        files: ^terraform/.*(\.tf|\.tfvars)$
  # {% endif %}
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.22.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
