# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        stages: [commit]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.23.0
    hooks:
      - id: yamllint
        stages: [commit]
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.33.0
    hooks:
      - id: cfn-python-lint
        files: ^([a-zA-Z0-9]|-)+\.(json|yml|yaml)$
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.22.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
